/*
 * KSP API
 *
 * API pro interakci s webem KSP.
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package kspapi_wrapper

type InlineResponse200 struct {
	// Dočasný API token
	Token string `json:"token"`
	// Platnost tokenu v sekundách
	ValiditySeconds int32 `json:"validity_seconds"`
}
