/*
 * KSP API
 *
 * API pro interakci s webem KSP. 
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package kspapi_wrapper
import (
	"time"
)

// Základní informace o jedné sérii a úlohách v nich.
type Series struct {
	// ID série
	Id string `json:"id"`
	// Čas zveřejnění zadání úloh. Ve formátu [dle RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
	TasksPublished time.Time `json:"tasks_published,omitempty"`
	// Termín odevzdání řešení. Ve formátu [dle RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
	Deadline time.Time `json:"deadline,omitempty"`
	// Termín odevzdání řešení za redukovaný počet bodů (druhý termín v KSP-Z).
	Deadline2 time.Time `json:"deadline2,omitempty"`
	Tasks []SeriesTasks `json:"tasks,omitempty"`
}
